Update electron to latest version
Wasn't working on Catalina but now it does.

Was getting these errors but they no longer exist with the latest
version of Electron.

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: $PWD/node_modules/vmd/node_modules/fsevents/build/Release/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: $PWD/node_modules/vmd/node_modules/fsevents/build/Release/fse.node
```

 Haven't tested thoroughly, just bumped the version and fixed the
 obvious issue.